package com.jieleo.projecta.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLLECT".
*/
public class CollectDao extends AbstractDao<Collect, Long> {

    public static final String TABLENAME = "COLLECT";

    /**
     * Properties of entity Collect.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CollectName = new Property(1, String.class, "collectName", false, "COLLECT_NAME");
        public final static Property CollectCoverIconUrl = new Property(2, String.class, "collectCoverIconUrl", false, "COLLECT_COVER_ICON_URL");
        public final static Property CollectContentUrl = new Property(3, String.class, "collectContentUrl", false, "COLLECT_CONTENT_URL");
    }


    public CollectDao(DaoConfig config) {
        super(config);
    }
    
    public CollectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLLECT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COLLECT_NAME\" TEXT," + // 1: collectName
                "\"COLLECT_COVER_ICON_URL\" TEXT," + // 2: collectCoverIconUrl
                "\"COLLECT_CONTENT_URL\" TEXT);"); // 3: collectContentUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLLECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Collect entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String collectName = entity.getCollectName();
        if (collectName != null) {
            stmt.bindString(2, collectName);
        }
 
        String collectCoverIconUrl = entity.getCollectCoverIconUrl();
        if (collectCoverIconUrl != null) {
            stmt.bindString(3, collectCoverIconUrl);
        }
 
        String collectContentUrl = entity.getCollectContentUrl();
        if (collectContentUrl != null) {
            stmt.bindString(4, collectContentUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Collect entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String collectName = entity.getCollectName();
        if (collectName != null) {
            stmt.bindString(2, collectName);
        }
 
        String collectCoverIconUrl = entity.getCollectCoverIconUrl();
        if (collectCoverIconUrl != null) {
            stmt.bindString(3, collectCoverIconUrl);
        }
 
        String collectContentUrl = entity.getCollectContentUrl();
        if (collectContentUrl != null) {
            stmt.bindString(4, collectContentUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Collect readEntity(Cursor cursor, int offset) {
        Collect entity = new Collect( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // collectName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // collectCoverIconUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // collectContentUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Collect entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCollectName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCollectCoverIconUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCollectContentUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Collect entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Collect entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Collect entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
