package com.jieleo.projecta.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLLECT_SINGLE".
*/
public class CollectSingleDao extends AbstractDao<CollectSingle, Long> {

    public static final String TABLENAME = "COLLECT_SINGLE";

    /**
     * Properties of entity CollectSingle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CoverImageUrl = new Property(1, String.class, "coverImageUrl", false, "COVER_IMAGE_URL");
        public final static Property DetailsUrl = new Property(2, String.class, "detailsUrl", false, "DETAILS_URL");
    }


    public CollectSingleDao(DaoConfig config) {
        super(config);
    }
    
    public CollectSingleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLLECT_SINGLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COVER_IMAGE_URL\" TEXT," + // 1: coverImageUrl
                "\"DETAILS_URL\" TEXT);"); // 2: detailsUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLLECT_SINGLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CollectSingle entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String coverImageUrl = entity.getCoverImageUrl();
        if (coverImageUrl != null) {
            stmt.bindString(2, coverImageUrl);
        }
 
        String detailsUrl = entity.getDetailsUrl();
        if (detailsUrl != null) {
            stmt.bindString(3, detailsUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CollectSingle entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String coverImageUrl = entity.getCoverImageUrl();
        if (coverImageUrl != null) {
            stmt.bindString(2, coverImageUrl);
        }
 
        String detailsUrl = entity.getDetailsUrl();
        if (detailsUrl != null) {
            stmt.bindString(3, detailsUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CollectSingle readEntity(Cursor cursor, int offset) {
        CollectSingle entity = new CollectSingle( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // coverImageUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // detailsUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CollectSingle entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCoverImageUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDetailsUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CollectSingle entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CollectSingle entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CollectSingle entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
