package com.jieleo.projecta.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jieleo.projecta.bean.greendao.Collection;
import com.jieleo.projecta.bean.greendao.Enshrine;
import com.jieleo.projecta.bean.greendao.Search;
import com.jieleo.projecta.bean.greendao.User;

import com.jieleo.projecta.bean.greendao.CollectionDao;
import com.jieleo.projecta.bean.greendao.EnshrineDao;
import com.jieleo.projecta.bean.greendao.SearchDao;
import com.jieleo.projecta.bean.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDaoConfig;
    private final DaoConfig enshrineDaoConfig;
    private final DaoConfig searchDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CollectionDao collectionDao;
    private final EnshrineDao enshrineDao;
    private final SearchDao searchDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        enshrineDaoConfig = daoConfigMap.get(EnshrineDao.class).clone();
        enshrineDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        collectionDao = new CollectionDao(collectionDaoConfig, this);
        enshrineDao = new EnshrineDao(enshrineDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Collection.class, collectionDao);
        registerDao(Enshrine.class, enshrineDao);
        registerDao(Search.class, searchDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        collectionDaoConfig.clearIdentityScope();
        enshrineDaoConfig.clearIdentityScope();
        searchDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

    public EnshrineDao getEnshrineDao() {
        return enshrineDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
