package com.jieleo.projecta.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jieleo.projecta.bean.greendao.Collection;
import com.jieleo.projecta.bean.greendao.CollectSingle;

import com.jieleo.projecta.bean.greendao.CollectionDao;
import com.jieleo.projecta.bean.greendao.CollectSingleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDaoConfig;
    private final DaoConfig collectSingleDaoConfig;

    private final CollectionDao collectionDao;
    private final CollectSingleDao collectSingleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        collectSingleDaoConfig = daoConfigMap.get(CollectSingleDao.class).clone();
        collectSingleDaoConfig.initIdentityScope(type);

        collectionDao = new CollectionDao(collectionDaoConfig, this);
        collectSingleDao = new CollectSingleDao(collectSingleDaoConfig, this);

        registerDao(Collection.class, collectionDao);
        registerDao(CollectSingle.class, collectSingleDao);
    }
    
    public void clear() {
        collectionDaoConfig.clearIdentityScope();
        collectSingleDaoConfig.clearIdentityScope();
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

    public CollectSingleDao getCollectSingleDao() {
        return collectSingleDao;
    }

}
