package com.jieleo.projecta.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ENSHRINE".
*/
public class EnshrineDao extends AbstractDao<Enshrine, Long> {

    public static final String TABLENAME = "ENSHRINE";

    /**
     * Properties of entity Enshrine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EnshireName = new Property(1, String.class, "enshireName", false, "ENSHIRE_NAME");
        public final static Property EnshrineCoverImage = new Property(2, String.class, "enshrineCoverImage", false, "ENSHRINE_COVER_IMAGE");
        public final static Property DetailsUrl = new Property(3, String.class, "detailsUrl", false, "DETAILS_URL");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
    }


    public EnshrineDao(DaoConfig config) {
        super(config);
    }
    
    public EnshrineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ENSHRINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ENSHIRE_NAME\" TEXT," + // 1: enshireName
                "\"ENSHRINE_COVER_IMAGE\" TEXT," + // 2: enshrineCoverImage
                "\"DETAILS_URL\" TEXT," + // 3: detailsUrl
                "\"TYPE\" INTEGER NOT NULL );"); // 4: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ENSHRINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Enshrine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String enshireName = entity.getEnshireName();
        if (enshireName != null) {
            stmt.bindString(2, enshireName);
        }
 
        String enshrineCoverImage = entity.getEnshrineCoverImage();
        if (enshrineCoverImage != null) {
            stmt.bindString(3, enshrineCoverImage);
        }
 
        String detailsUrl = entity.getDetailsUrl();
        if (detailsUrl != null) {
            stmt.bindString(4, detailsUrl);
        }
        stmt.bindLong(5, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Enshrine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String enshireName = entity.getEnshireName();
        if (enshireName != null) {
            stmt.bindString(2, enshireName);
        }
 
        String enshrineCoverImage = entity.getEnshrineCoverImage();
        if (enshrineCoverImage != null) {
            stmt.bindString(3, enshrineCoverImage);
        }
 
        String detailsUrl = entity.getDetailsUrl();
        if (detailsUrl != null) {
            stmt.bindString(4, detailsUrl);
        }
        stmt.bindLong(5, entity.getType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Enshrine readEntity(Cursor cursor, int offset) {
        Enshrine entity = new Enshrine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // enshireName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // enshrineCoverImage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // detailsUrl
            cursor.getInt(offset + 4) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Enshrine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEnshireName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEnshrineCoverImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDetailsUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Enshrine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Enshrine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Enshrine entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
